ams/ams/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('administration/', admin.site.urls),
    path('', include('accounts.urls')),
    path('asset/', include('asset.urls')),
    path('session_security/', include('session_security.urls')),
]

ams/asset/urls.py
from . import views 
from django.urls import path
from  .views import *
from asset.views import view_by_location
from django.contrib.auth import views as auth_views



urlpatterns = [
   # path('dashboard/', views.asset, name='asset'),
    path('acquisition/', AcquisitionCreateView.as_view(), name='acquisition'),
    path('view_acquisition/', AcquisitionListView.as_view(), name='view_acquisition'),
    path('update_acquisition/<str:pk>/', AcquisitionUpdateView.as_view(), name='update_acquisition'),
    path('acquisition_detail/<str:pk>/', AcquisitionDetailView.as_view(), name='acquisition_detail'),


    path('view_manufacturer/', ManufacturerListView.as_view(), name='view_manufacturer'),
    path('view_department/', DepartmentListView.as_view(), name='view_department'),
    path('transfers/' , TransferCreateView.as_view(), name='transfers'),
    path('view-transfer/', TransferListView.as_view(), name='view-transfer'),
    path('update-transfer/<str:pk>/', TransferUpdateView.as_view(), name='update-transfer'),
    path('written-off/', WrittenoffListView.as_view(), name='written-off'),
    path('view-users/', views.viewusers, name='view-users'),
    path('view-by-location/<str:location_id>/', views.view_by_location, name='view-by-location'),
    path('view-by-department/<str:dept_id>/', views.view_by_department, name='view-by-department'),


]

ams/asset/models.py
from django.db import models
from django.db.models.signals import *
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Manufacturer(models.Model):
    manufacturer_name = models.CharField(unique=True, max_length=200, null=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['manufacturer_name']

    def __str__(self):
        return self.manufacturer_name


class Acquisition(models.Model):
    asset_name = models.CharField(max_length=200, default=None)
    asset_number = models.CharField(max_length=200, unique=True, null=True, blank=True)
    serial_number = models.CharField(max_length=200, unique=True, null=True, blank=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    model = models.CharField(max_length=200, null=True, blank=True)
    purchased_from = models.CharField(max_length=200, null=True, blank=True)
    date_acquired = models.DateTimeField(default=timezone.now, null=True, blank=True)
    post_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    notes = models.TextField(default=None, null=True, blank=True)
    active = models.BooleanField(default=True, null=True, blank=True)

    class Meta:
        ordering = ['date_acquired']

    def __str__(self):
        #return "%s The Asset is " % self.asset_name
        return self.asset_name

    def get_absolute_url(self):
        return reverse('acquisition_detail', kwargs={'pk': self.pk})


class Department(models.Model):
    department_name = models.CharField(unique=True, max_length=200, null=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['department_name']

    def __str__(self):
        return self.department_name


class Location(models.Model):
    location_name = models.CharField(unique=True, max_length=200, null=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['location_name']

    def __str__(self):
        return self.location_name

    #def get_absolute_url(self):
        #return reverse('location_view')


class Transfer(models.Model):
    asset = models.OneToOneField(Acquisition, default=None, on_delete=models.CASCADE)
    assigned_to = models.CharField(max_length=200, null=True, blank=False)
    department_assigned = models.ForeignKey(Department, on_delete=models.CASCADE)
    location_assigned = models.ForeignKey(Location, on_delete=models.CASCADE)
    date_transferred = models.DateTimeField(default=timezone.now, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['date_transferred']

    def __str__(self):
        return  self.assigned_to + ' - ' + str(self.asset)
        #return "%s The Asset is " % self.asset_name

    def get_absolute_url(self):
        return reverse('view-transfer')

ams/asset/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView, DeleteView, UpdateView, CreateView, DetailView
)
from .models import Acquisition, Manufacturer, Department, Location, Transfer
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
def viewusers(request):
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'asset/view-users.html', context)


class AcquisitionCreateView(LoginRequiredMixin, CreateView):
    model = Acquisition
    template_name = 'asset/acquisition_form.html'
    fields = ['asset_name', 'asset_number', 'serial_number', 'manufacturer', 'model', 'purchased_from', 'notes']

    def form_valid(self, form):
        form.instance.post_by = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AcquisitionCreateView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'New Acquisition'
        return context


class AcquisitionUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Acquisition
    template_name = 'asset/acquisition_form.html'
    fields = ['asset_name', 'asset_number', 'serial_number', 'manufacturer', 'model', 'purchased_from', 'notes']

    def test_func(self):
        acquisition = self.get_object()
        if self.request.user == acquisition.post_by:
            return True
        return False


class AcquisitionDetailView(LoginRequiredMixin, DetailView):
    model = Acquisition

    def get_context_data(self, **kwargs):
        context = super(AcquisitionDetailView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'Acquisition Details'
        return context


class AcquisitionListView(LoginRequiredMixin, ListView):
    model = Acquisition
    queryset = Acquisition.objects.all()
    context_object_name = 'acquisitions'
    ordering = ['-date_acquired']
    template_name = 'asset/acquisition_view.html'

    def get_context_data(self, **kwargs):
        context = super(AcquisitionListView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'Acquisitions'
        return context


class ManufacturerListView(LoginRequiredMixin, ListView):
    model = Manufacturer
    queryset = Manufacturer.objects.all()
    context_object_name = 'manufacturers'
    ordering = ['manufacturer_name']
    template_name = 'asset/manufacturer_view.html'

    def get_context_data(self, **kwargs):
        context = super(ManufacturerListView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'Manufacturers'
        return context


class DepartmentListView(LoginRequiredMixin, ListView):
    model = Department
    queryset = Department.objects.all()
    context_object_name = 'departments'
    # ordering = ['manufacturer_name']
    template_name = 'asset/department_view.html'

    def get_context_data(self, **kwargs):
        context = super(DepartmentListView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'Departments'
        return context


class TransferCreateView(LoginRequiredMixin, CreateView):
    model = Transfer
    template_name = 'asset/transfer_form.html'

    fields = ['asset', 'assigned_to', 'department_assigned', 'location_assigned', 'is_active']

    def get_context_data(self, **kwargs):
        context = super(TransferCreateView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'New Transfer'
        return context


class TransferListView(LoginRequiredMixin, ListView):
    model = Transfer
    queryset = Transfer.objects.filter(is_active=True).all()
    context_object_name = 'transfers'
    ordering = ['-date_transferred']
    template_name = 'asset/transfer_view.html'

    def get_context_data(self, **kwargs):
        context = super(TransferListView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'All Transfers'
        return context


class TransferUpdateView(LoginRequiredMixin, UpdateView):
    model = Transfer
    template_name = 'asset/update_acquistion.html'
    fields = ['asset', 'assigned_to', 'department_assigned', 'location_assigned', 'is_active']

    def get_context_data(self, **kwargs):
        context = super(TransferUpdateView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'Update Transfers'
        return context


class WrittenoffListView(LoginRequiredMixin, ListView):
    model = Transfer
    queryset = Transfer.objects.filter(is_active=False)
    context_object_name = 'transfers'
    template_name = 'asset/writtenoff.html'

    def get_context_data(self, **kwargs):
        context = super(WrittenoffListView, self).get_context_data(**kwargs)
        # Add context data to pass to template
        context['title'] = 'Board of Servey'
        return context


@login_required(login_url='login')
def view_by_location(request, location_id):
    location = Location.objects.get(pk=location_id)
    context = {'location': location}
    return render(request, 'asset/location_cat_view.html', context)


@login_required(login_url='login')
def view_by_department(request, dept_id):
    department = Department.objects.get(pk=dept_id)
    context = {'department': department}
    return render(request, 'asset/department_cat_view.html', context)

ams/asset/templates/asset/acquisition_detail.html
{% extends 'asset/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{%block content%}
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Acquisition Detail - <span class="text-primary">{{object.asset_name|upper}}</span></h3>
        </div>
      <!-- /.card-header -->
      <div class="card-body">
          <div class="row">
              <div class="col-md-6">
                <h4>Name: <span class="text-primary">{{object.asset_name}}</span></h4>
                <h4>Asset Number: <span class="text-primary" >{{object.asset_number|upper}}</span></h4>
                <h4>Serial Number: <span class="text-primary" >{{object.serial_number|upper}}</span></h4>
                <h4>Manufacturer: <span class="text-primary" >{{object.manufacturer}}</span></h4>
                <h4>Model: <span class="text-primary" >{{object.model}}</span></h4>

              </div>
              <div class="col-md-6">
                <h4>Purchased From: <span class="text-primary" >{{object.purchased_from}}</span></h4>
                <h4>Aquired: <span class="text-primary" >{{object.date_acquired|date:"F d, Y"}}</span></h4>
                <h4>Added By: <span class="text-primary" >{{object.post_by.first_name}} {{object.post_by.last_name}}</span></h4>
                <h2 class="text-danger">Notes</h2>

                <p>{{object.notes}}</p>
            </div>

            <div>
                <a class="btn btn btn-warning" href="{% url 'update_acquisition' acquisition.id %} ">Edit</a>
                <a class="btn btn btn-info" href="{% url 'view_acquisition' %}">Back</a>
            </div>
            
          </div>
      </div>
    </div>
{%endblock content%}
<a class="btn btn btn-warning" href="">Edit</a>
<a class="btn btn btn-success" href="{% url 'view_acquisition' %}">Back</a>

ams/asset/templates/asset/acquisition_form.html
{% extends 'asset/base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{%block content%}
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">New Acquisition</h3>
  </div>
      <!-- /.card-header -->
      <div class="card-body">
          <form method="post" action="">
              <div class="row">
                  <div class="col-md-6">
                      {%csrf_token%}
                      {{form|crispy}}
                  </div>
              </div>
              <div class="form-group">
                    <button class="btn btn-primary" type="submit">Save</button>
              </div>
          </form>
      </div>

    </div>
{%endblock content%}

ams/asset/templates/asset/acquisition_view.html
{% extends 'asset/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{%block title%} JNHT-AMS All Acquisitions {%endblock%}
{%block content%}

<div class="card">
    <div class="card-header">
      <h3 class="card-title">All Acquisitions</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Asset Name</th>
            <th>Asset Number</th>
            <th>Serial Number</th>
            <th>Manufacturer</th>
            <th>Model</th>
            <th>Purchased From</th>
            <th>Date Acquired</th>
        
        </tr>
        </thead>
        <tbody>

            {% for acquisition in acquisitions %}

            <tr>
                <td><a href="{% url 'acquisition_detail' acquisition.id %} "> {{acquisition.asset_name}}</a></td>
                <td>{{acquisition.asset_number|upper}}</td>
                <td>{{acquisition.serial_number|upper}}</td>
                <td>{{acquisition.manufacturer}}</td>
                <td>{{acquisition.model}}</td>
                <td><a href="">{{acquisition.purchased_from}}</a></td>
                <td>{{acquisition.date_acquired|date:"F d, Y"}}</td>
            

            </tr>
{% endfor %}
       
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>


  {%endblock content%}

ams/asset/templates/asset/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<title>{%block title %} JNHT-AMS- Home{%endblock%}</title>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'accounts/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'accounts/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'accounts/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'accounts/plugins/datatables-buttons/css/buttons.bootstrap4.min.css ' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'accounts/dist/css/adminlte.min.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet">
    <style>
      #logo{
        font-family: 'Merienda', cursive;

        }
  </style>
</head>
<body class="hold-transition sidebar-mini ">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{%url 'home' %}" class="nav-link">Home</a>
      </li>
      <!--<li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>-->
    </ul>

    <!-- SEARCH FORM -->
    <!--<form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>-->

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="" href="#" role="button">
          <span> <i class="fa fa-user" aria-hidden="true"></i> {{request.user.first_name}} {{request.user.last_name}}</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" data-widget="" href="#" role="button">
          <span> <i class="fa fa-clock" aria-hidden="true"></i> {{request.user.last_login}} </span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" data-widget="" href="{% url 'logout' %}" role="button">
          <span><i class="fa fa-lock" aria-hidden="true"></i> Logout </span>
        </a>
      </li>


      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'home' %}" class="brand-link">
      <!--<img src="{% static ' accounts/images/logo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">-->
      <!--<span class="brand-text font-weight-light">AdminLTE 3</span>-->
      <h1 id="logo">JNHT AMS</h1>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="" class="img-circle elevation-2" alt="">
        </div>
        <div class="info">
          <span class="text-primary"><i class="fa fa-user" aria-hidden="true"></i> {{request.user.first_name}} {{request.user.last_name}}</span>
        </div>
      </div>

      <!-- SidebarSearch Form -->
     <!-- <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Acquisition
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'acquisition' %}" class="nav-link ">
                  <i class="far fa-circle nav-icon"></i>
                  <p>New Acquisition</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'view_acquisition' %}" class="nav-link ">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Acquisitions</p>
                </a>
              </li>

            </ul>
          </li>

          <li class="nav-item menu-open">
            <a href="#" class="nav-link ">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Manufacturer
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'view_manufacturer' %}" class="nav-link ">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Manufacturers</p>
                </a>
              </li>

            </ul>
          </li>

          <li class="nav-item menu-open">
            <a href="#" class="nav-link ">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Department
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'view_department' %}" class="nav-link ">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View Departments</p>
                </a>
              </li>

            </ul>
          </li>

          
          <li class="nav-item menu-open">
            <a href="#" class="nav-link ">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Transfer
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'transfers' %}" class="nav-link ">
                  <i class="far fa-circle nav-icon"></i>
                  <p>New Transfer</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'view-transfer'%}" class="nav-link ">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Current Assets</p>
                </a>
              </li>

            </ul>
          </li>

          
          <li class="nav-item menu-open">
            <a href="#" class="nav-link ">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Board of Servey
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'written-off' %}" class="nav-link  ">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Written off Items</p>
                </a>
              </li>

            </ul>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
          {%block content %}
            
            
            {%endblock content%}
        
       
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <!--<aside class="control-sidebar control-sidebar-dark">
     Control sidebar content goes here 
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>-->
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Developed By <a href="mailto: SUCCESS1876@OUTLOOK.COM">Ricardo Webley - Intern 2020</a>
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2020 <a href="http://jnht.com">Jamaica National Heritage Trust</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'accounts/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'accounts/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'accounts/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'accounts/plugins/datatables/jquery.dataTables.min.js ' %} "></script>
<script src="{% static 'accounts/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'accounts/plugins/datatables-responsive/js/dataTables.responsive.min.js'%}"></script>
<script src="{% static 'accounts/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'accounts/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'accounts/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'accounts/plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'accounts/plugins/pdfmake/pdfmake.min.js '%}"></script>
<script src="{% static 'accounts/plugins/pdfmake/vfs_fonts.js '%}"></script>
<script src="{% static 'accounts/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'accounts/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'accounts/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'accounts/dist/js/adminlte.min.js' %}"></script>
{% include 'session_security/all.html' %}
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
</body>
</html>

ams/asset/templates/asset/department_cat_view.html
{% extends 'asset/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{%block title%} JNHT-AMS Assets in {{department.department_name}} {%endblock%}
{%block content%}

<div class="card">
    <div class="card-header">
      <h3 class="card-title">Assets Located in <b class="text-danger">{{department.department_name}}</b></h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Name</th>
            <th>Asset Number</th>
            <th>Serial Number</th>
            <th>Assigned To</th>
        </tr>
        </thead>
        <tbody>
            {% for dept in department.transfer_set.all %}

            <tr>
                <td>{{dept.asset}}</td>
                <td>{{dept.asset.asset_number|upper}}</td>
                <td>{{dept.asset.serial_number|upper}}</td>
                <td>{{dept.assigned_to}}</td>
            </tr>
{% endfor %}


        </tfoot>

      </table>

    </div>

  </div>


  {%endblock content%}

ams/asset/templates/asset/location_cat_view.html
{% extends 'asset/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{%block title%} JNHT-AMS Assets in {{location.location_name}} {%endblock%}
{%block content%}

<div class="card">
    <div class="card-header">
      <h3 class="card-title">Assets Located in <b class="text-danger">{{location.location_name}}</b></h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Name</th>
            <th>Asset Number</th>
            <th>Serial Number</th>
            <th>Assigned To</th>
        </tr>
        </thead>
        <tbody>
            {% for trans in location.transfer_set.all %}

            <tr>
                <td>{{trans.asset}}</td>
                <td>{{trans.asset.asset_number|upper}}</td>
                <td>{{trans.asset.serial_number|upper}}</td>
                <td>{{trans.assigned_to}}</td>
            </tr>
{% endfor %}

       
        </tfoot>
      </table>
    </div>
    <!-- /.card-body -->
  </div>


  {%endblock content%}